spring.application.name=jobtracker

spring.datasource.url=jdbc:postgresql://localhost:5432/job_tracker
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=900000

app.refresh-token.expiration=604800000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized