spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

logging.level.root=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

management.endpoint.health.show-details=never

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.forward-headers-strategy=framework

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
server.port=${PORT:8080}

server.error.include-message=never
server.error.include-binding-error=never
server.error.include-stacktrace=never
server.error.include-exception=false


spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
